# Generated by Django 5.2.4 on 2025-07-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
