# Generated by Django 5.2.4 on 2025-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='btc_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
